apiVersion: v1
kind: Service
metadata:
  name: arcadia-app2-svc
  namespace: arcadia
  labels:
    app: arcadia-app2-svc
    cis.f5.com/as3-tenant: arcadia-tenant
    cis.f5.com/as3-app: arcadia-app
    cis.f5.com/as3-pool: arcadia-app2-pool
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: arcadia-app2
---
apiVersion: v1
kind: Service
metadata:
  name: arcadia-app3-svc
  namespace: arcadia
  labels:
    app: arcadia-app3-svc
    cis.f5.com/as3-tenant: arcadia-tenant
    cis.f5.com/as3-app: arcadia-app
    cis.f5.com/as3-pool: arcadia-app3-pool
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: arcadia-app3
---
apiVersion: v1
kind: Service
metadata:
  name: arcadia-backend-svc
  namespace: arcadia
  labels:
    app: arcadia-backend-svc
    cis.f5.com/as3-tenant: arcadia-tenant
    cis.f5.com/as3-app: arcadia-app
    cis.f5.com/as3-pool: arcadia-backend-pool
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: arcadia-backend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: arcadia-mainapp-svc
    cis.f5.com/as3-tenant: arcadia-tenant
    cis.f5.com/as3-app: arcadia-app
    cis.f5.com/as3-pool: arcadia-mainapp-pool
  name: arcadia-mainapp-svc
  namespace: arcadia
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: arcadia-mainapp
---
