apiVersion: v1
kind: ConfigMap
metadata:
  name: arcadia-cm
  namespace: arcadia
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.52.0",
        "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
        "label": "http",
        "remark": "A1 example",
        "arcadia-tenant": {
          "class": "Tenant",
          "arcadia-app": {
            "class": "Application",
            "template": "generic",
            "arcadia-VS": {
              "class": "Service_HTTPS",
              "virtualAddresses": [
                "10.1.10.101"
              ],
              "pool": "arcadia-mainapp-pool",
              "virtualPort": 443,
              "policyWAF": {
                "bigip": "/Common/arcadia-waf"
              },
              "securityLogProfiles": [
                {
                  "bigip": "/Common/Log all requests"
                }
              ],
              "serverTLS": {
                "bigip": "/Common/clientssl"
              },
              "snat": {
                "bigip": "/Common/arcadia-snatpool"
              },
              "policyEndpoint": "forward_policy"
            },
            "arcadia-app2-pool": {
              "class": "Pool",
              "monitors": [
                "http"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
                {
                  "servicePort": 8080,
                  "serverAddresses": []
                }
              ]
            },
            "arcadia-app3-pool": {
                "class": "Pool",
                "monitors": [
                  "http"
                ],
                "loadBalancingMode": "least-connections-member",
                "members": [
                  {
                    "servicePort": 8080,
                    "serverAddresses": []
                  }
                ]
            },
            "arcadia-backend-pool": {
                "class": "Pool",
                "monitors": [
                  "http"
                ],
                "loadBalancingMode": "least-connections-member",
                "members": [
                  {
                    "servicePort": 8080,
                    "serverAddresses": []
                  }
                ]
            },
            "arcadia-mainapp-pool": {
              "class": "Pool",
              "monitors": [
                "http"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
                {
                  "servicePort": 8080,
                  "serverAddresses": []
                }
              ]
            },
            "forward_policy": {
              "class": "Endpoint_Policy",
              "rules": [
                {
                  "name": "forward_to_app2",
                  "conditions": [
                    {
                      "type": "httpHost",
                      "event": "request",
                      "host": {
                        "operand": "ends-with",
                        "values": ["arcadia.f5demo"]
                      },
                      "caseSensitive": true
                    },
                    {
                      "type": "httpUri",
                      "path": {
                        "operand": "starts-with",
                        "values": ["/api"]
                      }
                    }
                  ],
                  "actions": [
                    {
                      "type": "forward",
                      "event": "request",
                      "select": {
                        "pool": {
                          "use": "arcadia-app2-pool"
                        }
                      }
                    }
                  ]
                },
                {
                    "name": "forward_to_app3",
                    "conditions": [
                      {
                        "type": "httpHost",
                        "event": "request",
                        "host": {
                          "operand": "ends-with",
                          "values": ["arcadia.f5demo"]
                        },
                        "caseSensitive": true
                      },
                      {
                        "type": "httpUri",
                        "path": {
                          "operand": "starts-with",
                          "values": ["/app3"]
                        }
                      }
                    ],
                    "actions": [
                      {
                        "type": "forward",
                        "event": "request",
                        "select": {
                          "pool": {
                            "use": "arcadia-app3-pool"
                          }
                        }
                      }
                    ]
                },                
                {
                    "name": "forward_to_backend",
                    "conditions": [
                      {
                        "type": "httpHost",
                        "event": "request",
                        "host": {
                          "operand": "ends-with",
                          "values": ["arcadia.f5demo"]
                        },
                        "caseSensitive": true
                      },
                      {
                        "type": "httpUri",
                        "path": {
                          "operand": "starts-with",
                          "values": ["/files"]
                        }
                      }
                    ],
                    "actions": [
                      {
                        "type": "forward",
                        "event": "request",
                        "select": {
                          "pool": {
                            "use": "arcadia-backend-pool"
                          }
                        }
                      }
                    ]
                },
                {
                  "name": "forward_to_mainapp",
                  "conditions": [
                    {
                      "type": "httpHost",
                      "event": "request",
                      "host": {
                        "operand": "ends-with",
                        "values": ["arcadia.f5demo"]
                      },
                      "caseSensitive": true
                    }
                  ],
                  "actions": [
                    {
                      "type": "forward",
                      "event": "request",
                      "select": {
                        "pool": {
                          "use": "arcadia-mainapp-pool"
                        }
                      }
                    }
                  ]
                }
              ]
            }
          }
        }
      }
    }
